# Generated by Django 3.0.2 on 2020-02-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('tab_bord', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cahier', models.CharField(max_length=25)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('nom_niveau', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cahier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.TextBook')),
                ('responsable_pedagogique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Professeur')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Niveau'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='cahier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.TextBook'),
        ),
        migrations.AddField(
            model_name='cours',
            name='etudiant',
            field=models.ManyToManyField(through='PlanninGO.Note', to='PlanninGO.Etudiant'),
        ),
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Professeur'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanninGO.Salle'),
        ),
    ]
