# Generated by Django 3.0.2 on 2020-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanninGO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='nom_cahier',
            field=models.CharField(default='', editable=False, max_length=25),
        ),
    ]
